const asocijacijePrimeri =[
    {
        A1:'BRAZIL',
        A2:'ETIOPIA',
        A3:'JUTRO',
        A4:'SOLJA',
        A5:'KAFA',
        B1:'TRI',
        B2:'KOORDINATE',
        B3:'PIKSEL',
        B4:'INTERPUNKCIJA',
        B5:'TACKA',
        C1:'RUNO',
        C2:'VUNA',
        C3:'MERINO',
        C4:'ASKA',
        C5:'OVCA',
        D1:'VUDU',
        D2:'VRACARA',
        D3:'CAROBNJAK',
        D4:'LJUBAV',
        D5:'MAGIJA',
        resenje:'CRNA'
    },{
        A1:'OSMEH',
        A2:'DUNAV',
        A3:'IZBOR',
        A4:'PROSTRAN',
        A5:'SIROK',
        B1:'LIPE',
        B2:'KUCE',
        B3:'GLAVNA',
        B4:'SLEPA',
        B5:'ULICA',
        C1:'SAGA',
        C2:'BOGOVI',
        C3:'PRVI',
        C4:'VECE',
        C5:'SUMRAK',
        D1:'TABAK',
        D2:'ROTO',
        D3:'OFSET',
        D4:'DUBOKA',
        D5:'STAMPA',
        resenje:'BULEVAR'
    },{
        A1:'OFICIR',
        A2:'AKT',
        A3:'SVRSEN',
        A4:'RITUAL',
        A5:'CIN',
        B1:'DRVO',
        B2:'SAPUTNIK',
        B3:'SREDINA',
        B4:'VEK',
        B5:'ZIVOT',
        C1:'PREOKRET',
        C2:'KAPITAL',
        C3:'MOMENT',
        C4:'KOPERNIK',
        C5:'OBRT',
        D1:'CIGARETA',
        D2:'RUCAK',
        D3:'PREDAH',
        D4:'DOM ZDRAVLJA',
        D5:'PAUZA',
        resenje:'DRAMA'  
    },{
        A1:'SAOBRACAJ',
        A2:'FAUL',
        A3:'POSTUPAK',
        A4:'PRAVILA',
        A5:'PREKRSAJ',
        B1:'OPSTINA',
        B2:'STARCI',
        B3:'NASTAVNIK',
        B4:'TUZILAC',
        B5:'VECE',
        C1:'SRETENJE',
        C2:'VIDOVDAN',
        C3:'BRANITELJ',
        C4:'PRAVO',
        C5:'USTAV',
        D1:'SESTRA',
        D2:'OBRAZ',
        D3:'KRST',
        D4:'REC',
        D5:'CAST',
        resenje:'SUD'    
    },{
        A1:'ISTINA',
        A2:'PODRUM',
        A3:'MUSICA',
        A4:'BURE',
        A5:'VINO',
        B1:'SKANDINAVIJA',
        B2:'KRALJEVINA',
        B3:'NOBEL',
        B4:'OSLO',
        B5:'SVEDSKA',
        C1:'BATERIJA',
        C2:'PETROLEJ',
        C3:'ALADIN',
        C4:'SIGNAL',
        C5:'LAMPA',
        D1:'ZAOKRUZENI',
        D2:'OBLI',
        D3:'LOPTA',
        D4:'TOCAK',
        D5:'OKRUGLi',
        resenje:'STO'     
    }
]
const upamtiAsocijacije = function (asocijacijePrimeri) {
    localStorage.setItem("Asocijacije", JSON.stringify(asocijacijePrimeri));
  };
  function randomIntFromInterval(min, max) { // min and max included 
    return Math.floor(Math.random() * (max - min + 1) + min)
  }
  //const rnd = randomIntFromInterval(0,4);
  //randomAsocijacija = asocijacijePrimeri[rnd]
  //console.log(randomAsocijacija)
  
  upamtiAsocijacije(asocijacijePrimeri);